// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Util$ReasonTree = require("./Util.bs.js");

console.log("Hello, BuckleScript and Reason!");

console.log(Util$ReasonTree.getAbsolutePath("../"));

console.log(Util$ReasonTree.printDir(0, "node_modules", "../"));

/*  Not a pure module */
